version:  '3'
services:
    nginx-service:
        container_name: nginx-container
        image: nginx:stable-alpine
        volumes:
            - ./app:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - '8080:80'
        depends_on:
            - php-service
        networks:
            - nginx-php-mariadb-phpmyadmin

    php-service:
        container_name: php-container
        env_file:
            - .env
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./app:/var/www
        command: /var/www/entrypoint.sh
        ports:
            - '9000:9000'
        networks:
            - nginx-php-mariadb-phpmyadmin

    mariadb-service:
        container_name: mariadb-container
        image: mariadb:latest
        volumes:
            - ./docker/database/data/app:/var/lib/mysql
        env_file:
            - .env
        networks:
            - nginx-php-mariadb-phpmyadmin
        ports:
            - '3306:3306'

    phpmyadmin-service:
        container_name: phpmyadmin-container
        image: phpmyadmin/phpmyadmin
        networks:
            - nginx-php-mariadb-phpmyadmin
        ports:
            - '8888:80'
        links:
            - 'mariadb-service:db'

networks:
    nginx-php-mariadb-phpmyadmin: