version:  '3'
services:
    nginx-service:
        image: nginx:stable-alpine
        #container_name: nginx-container
        ports:
            - '80:80'
        volumes:
            - ./app:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php-service
        networks:
            - nginx-php-mariadb-phpmyadmin-node

    php-service:
        #container_name: php-container
        env_file:
            - .env
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        ports:
            - '9000:9000'
        volumes:
            - ./app:/var/www
        command: /var/www/entrypoint_php.sh
        networks:
            - nginx-php-mariadb-phpmyadmin-node

    mariadb-service:
        image: mariadb:latest
        #container_name: mariadb-container
        ports:
            - '3306:3306'
        volumes:
            - ./docker/database/data/app:/var/lib/mysql
        env_file:
            - .env
        networks:
            - nginx-php-mariadb-phpmyadmin-node

    phpmyadmin-service:
        image: phpmyadmin/phpmyadmin
        #container_name: phpmyadmin-container
        ports:
            - '8888:80'
        links:
            - 'mariadb-service:db'
        networks:
            - nginx-php-mariadb-phpmyadmin-node

    node-service:
        image: node:latest
        volumes:
            - ./app:/var/www
        working_dir: /var/www
        tty: true
        command: /var/www/entrypoint_node.sh
        networks:
            - nginx-php-mariadb-phpmyadmin-node

networks:
    nginx-php-mariadb-phpmyadmin-node: