version:  '3.3'
services:
    nginx:
        container_name: todo_nginx
        image: nginx:1.19.0-alpine
        build: docker/nginx
        volumes:
            - ./app/public/:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - '81:80'
        depends_on:
            - php

    php:
        container_name: todo_php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./app:/var/www
        command: /var/www/entrypoint.sh